version: "3.8"

services:
  phi-annotator:
    image: docker.synapse.org/syn22277123/phi-annotator-spark:1..0.0
    build:
      context: server
      dockerfile: Dockerfile
    container_name: phi-annotator
    environment:
      - SPARK_LICENSE_KEY
      - SPARK_LICENSE_SECRET
      - SPARK_AWS_ACCESS_KEY_ID
      - SPARK_AWS_SECRET_ACCESS_KEY
      - SPARK_JSL_VERSION
      - SPARK_PUBLIC_VERSION
    # networks:
    #   - nlpsandbox-internal

  nginx:
    image: nginx:1.19.6-alpine
    container_name: nginx
    restart: always
    environment:
      - TOOL_HOST=phi-annotator
      - TOOL_PORT=8081
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
    # networks:
    #   - nlpsandbox
    #   - nlpsandbox-internal
    ports:
      - "80:80"
    depends_on:
      - phi-annotator

networks:
  nlpsandbox:
  # nlpsandbox-internal:
  #   internal: true
